import base64

import numpy as np
import pytest

from colab_viz.domains.d7_visualization.readers import describe_field, read_field


_GRIB1 = "R1JJQgAAkAEAADSAYoD/gIJkA1IaAQEAAAEAAAAAAAAVAAAAAAAAAAAAAAAAAAAAAQECBAEwMDAxAAAAAAAgAP8AAAQAAwAH0AAAAIAAAAAAC7gD6APoAAAAAAAAADAIgBRDERJmGAAAZhAAZiAAZjAAZkAAZlAAZmAAZnAAZoAAZpAAZqAAZrAAZgA3Nzc3R1JJQgAAkAEAADSAYoD/gIJkA1IaAQEAAAEGAAAAAAAVAAAAAAAAAAAAAAAAAAAAAQECBAEwMDAxAAAAAAAgAP8AAAQAAwAH0AAAAIAAAAAAC7gD6APoAAAAAAAAADAIgBRDElJmGAAAZhAAZiAAZjAAZkAAZlAAZmAAZnAAZoAAZpAAZqAAZrAAZgA3Nzc3R1JJQgAAkAEAADSAYoD/gIJkAfQaAQEAAAEAAAAAAAAVAAAAAAAAAAAAAAAAAAAAAQECBAEwMDAxAAAAAAAgAP8AAAQAAwAH0AAAAIAAAAAAC7gD6APoAAAAAAAAADAIgBRDE5JmGAAAZhAAZiAAZjAAZkAAZlAAZmAAZnAAZoAAZpAAZqAAZrAAZgA3Nzc3R1JJQgAAkAEAADSAYoD/gIJkAfQaAQEAAAEGAAAAAAAVAAAAAAAAAAAAAAAAAAAAAQECBAEwMDAxAAAAAAAgAP8AAAQAAwAH0AAAAIAAAAAAC7gD6APoAAAAAAAAADAIgBRDFNJmGAAAZhAAZiAAZjAAZkAAZlAAZmAAZnAAZoAAZpAAZqAAZrAAZgA3Nzc3"
_GRIB2 = "R1JJQv//AAIAAAAAAAAA1wAAABUBAGIAAAQAAQfqAQEAAAAAAgAAAEgDAAAAAAwAAAAABv///////////////////wAAAAQAAAADAAAAAP////8AHoSAAAAAADAAAAAAAC3GwAAPQkAAD0JAAAAAACIEAAAAAAAAAP+AAAAAAQAAAABkAAABTAj///////8AAAAVBQAAAAwAAEOIkzOAFAAAGAAAAAAGBv8AAAApBwAABhAABiAABjAABkAABlAABmAABnAABoAABpAABqAABrAABjc3NzdHUklC//8AAgAAAAAAAADXAAAAFQEAYgAABAABB+oBAQAAAAACAAAASAMAAAAADAAAAAAG////////////////////AAAABAAAAAMAAAAA/////wAehIAAAAAAMAAAAAAALcbAAA9CQAAPQkAAAAAAIgQAAAAAAAAA/4AAAAABAAAABmQAAAFMCP///////wAAABUFAAAADAAAQ5KTM4AUAAAYAAAAAAYG/wAAACkHAAAGEAAGIAAGMAAGQAAGUAAGYAAGcAAGgAAGkAAGoAAGsAAGNzc3N0dSSUL//wACAAAAAAAAANcAAAAVAQBiAAAEAAEH6gEBAAAAAAIAAABIAwAAAAAMAAAAAAb///////////////////8AAAAEAAAAAwAAAAD/////AB6EgAAAAAAwAAAAAAAtxsAAD0JAAA9CQAAAAAAiBAAAAAAAAAD/gAAAAAEAAAAAZAAAAMNQ////////AAAAFQUAAAAMAABDnJMzgBQAABgAAAAABgb/AAAAKQcAAAYQAAYgAAYwAAZAAAZQAAZgAAZwAAaAAAaQAAagAAawAAY3Nzc3R1JJQv//AAIAAAAAAAAA1wAAABUBAGIAAAQAAQfqAQEAAAAAAgAAAEgDAAAAAAwAAAAABv///////////////////wAAAAQAAAADAAAAAP////8AHoSAAAAAADAAAAAAAC3GwAAPQkAAD0JAAAAAACIEAAAAAAAAAP+AAAAAAQAAAAZkAAAAw1D///////8AAAAVBQAAAAwAAEOmkzOAFAAAGAAAAAAGBv8AAAApBwAABhAABiAABjAABkAABlAABmAABnAABoAABpAABqAABrAABjc3Nzc="


@pytest.mark.parametrize(("name", "payload"), (("fixture.grib1", _GRIB1), ("fixture.grib2", _GRIB2)))
def test_grib_editions_keep_time_and_level_selections_distinct(tmp_path, name, payload):
    path = tmp_path / name
    path.write_bytes(base64.b64decode(payload))
    fmt, variables, instants = describe_field(path)
    assert fmt == "GRIB" and instants == []
    assert len(variables) == 4 and len(set(variables)) == 4
    assert len({v.split("|")[1] for v in variables}) == 2
    assert len({v.split("|")[2] for v in variables}) == 2
    means = [float(np.nanmean(read_field(path, variable=v)[1].values)) for v in variables]
    assert means == pytest.approx([5.5, 25.5, 45.5, 65.5], abs=1e-4)
