#!/usr/bin/env python3
"""generated-up-to-date 게이트 엔진 — 생성물이 계약보다 낡지 않았음을 증명한다.

정본 = contracts/codegen/manifest.toml (생성물 등기부).

검사 3종:
  ① 등기부 자체 — 부재·파싱 불가·엔트리 0건은 전부 red (빈 등기부 ≠ green).
  ② 엔트리별 재생성 diff — source 를 command 로 다시 생성해 커밋본과 byte-diff.
     source 부재·output 부재·생성 실패·불일치(낡음/손수정) 전부 red.
  ③ 마커 스윕 — 등기부 밖에서 「generated」 마커를 달고 있는 파일은 red.
     codegen 통제 밖의 자칭 생성물은 손수정 금지 규칙(CLAUDE.md 규칙 7)을
     아무도 지켜줄 수 없는 파일이다.

원칙 (CLAUDE.md §4): 도구 부재·대상 0건은 skip 이 아니라 red. green-by-skip 없음.

env 오버라이드 (selftest 전용):
  COLAB_GEN_MANIFEST   등기부 경로 (기본 contracts/codegen/manifest.toml)
  COLAB_GEN_ROOT       source/output 해석·command 실행의 기준 디렉터리 (기본 레포 루트)
  COLAB_GEN_SCAN_ROOTS 마커 스윕 대상 (':' 구분, 기본 services:frontend/src:db)
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

MARKER_RE = re.compile(
    r"auto-?generated|@generated|do not edit|autogenerated", re.IGNORECASE
)
SCAN_SUFFIXES = {".py", ".ts", ".tsx", ".js", ".mjs", ".cjs", ".sql"}
SKIP_DIRS = {"node_modules", "dist", ".venv", "__pycache__", ".git", "build"}
MARKER_HEAD_LINES = 30  # 마커는 파일 머리에 있다 — 전체 스캔은 비용만 든다

errors: list[str] = []


def red(msg: str) -> None:
    errors.append(msg)
    print(f"::error::generated-up-to-date red — {msg}")


def load_manifest(path: Path) -> list[dict] | None:
    if not path.is_file():
        red(f"등기부가 없다: {path} — 등기부 부재는 통과가 아니다")
        return None
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as e:
        red(f"등기부 파싱 실패: {path} — {e}")
        return None
    entries = data.get("output", [])
    if not entries:
        red(f"등기부 엔트리 0건: {path} — 빈 등기부는 green 이 아니다 (대상 0건 = red)")
        return None
    return entries


def check_entry(entry: dict, root: Path) -> None:
    eid = entry.get("id", "<no-id>")
    missing = [k for k in ("source", "output", "command") if not entry.get(k)]
    if missing:
        red(f"[{eid}] 등기부 엔트리에 {missing} 가 없다")
        return
    source = root / entry["source"]
    output = root / entry["output"]
    if not source.is_file():
        red(f"[{eid}] source 가 없다: {entry['source']}")
        return
    if not output.is_file():
        red(f"[{eid}] 커밋된 생성물이 없다: {entry['output']} — 생성물은 커밋한다 (contracts/README.md 규칙 3)")
        return
    with tempfile.NamedTemporaryFile(suffix=output.suffix, delete=False) as tf:
        tmp = Path(tf.name)
    try:
        cmd = entry["command"].replace("{OUT}", str(tmp))
        proc = subprocess.run(
            ["bash", "-c", cmd], cwd=root, capture_output=True, text=True, timeout=300
        )
        if proc.returncode != 0:
            red(f"[{eid}] 재생성 실패 (exit {proc.returncode}): {proc.stderr.strip()[:400]}")
            return
        regen = tmp.read_bytes() if tmp.is_file() else None
        if regen is None:
            red(f"[{eid}] 재생성 명령이 산출물을 만들지 않았다")
            return
        committed = output.read_bytes()
        if regen != committed:
            red(
                f"[{eid}] 생성물이 계약과 다르다: {entry['output']} — "
                f"낡았거나 손으로 고쳐졌다. 재생성해 커밋하라 (command 참조, 손수정 금지)"
            )
            _print_diff_head(tmp, output)
    finally:
        tmp.unlink(missing_ok=True)


def _print_diff_head(regen: Path, committed: Path) -> None:
    try:
        d = subprocess.run(
            ["diff", "-u", str(committed), str(regen)], capture_output=True, text=True
        )
        for line in d.stdout.splitlines()[:20]:
            print(f"           {line}")
    except OSError:
        pass


def marker_sweep(root: Path, scan_roots: list[str], registered: set[Path]) -> None:
    for sr in scan_roots:
        base = root / sr
        if not base.is_dir():
            continue
        for p in sorted(base.rglob("*")):
            if not p.is_file() or p.suffix not in SCAN_SUFFIXES:
                continue
            if any(part in SKIP_DIRS for part in p.parts):
                continue
            if p.resolve() in registered:
                continue
            try:
                head = "".join(
                    line
                    for _, line in zip(
                        range(MARKER_HEAD_LINES), p.open(encoding="utf-8", errors="ignore")
                    )
                )
            except OSError:
                continue
            if MARKER_RE.search(head):
                red(
                    f"등기부 밖의 자칭 생성물: {p.relative_to(root)} — "
                    f"generated 마커가 있는데 contracts/codegen/manifest.toml 에 없다"
                )


def main() -> int:
    manifest_path = Path(
        os.environ.get("COLAB_GEN_MANIFEST", REPO_ROOT / "contracts/codegen/manifest.toml")
    )
    root = Path(os.environ.get("COLAB_GEN_ROOT", REPO_ROOT))
    scan_roots = os.environ.get("COLAB_GEN_SCAN_ROOTS", "services:frontend/src:db").split(":")

    entries = load_manifest(manifest_path)
    registered: set[Path] = set()
    if entries is not None:
        for e in entries:
            if e.get("output"):
                registered.add((root / e["output"]).resolve())
        for e in entries:
            check_entry(e, root)
        marker_sweep(root, scan_roots, registered)

    if errors:
        print(f"generated-up-to-date red — {len(errors)}건")
        return 1
    print(f"generated-up-to-date green — 등기부 {len(entries)}건 전부 재생성 일치, 등기부 밖 자칭 생성물 0건.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
