import React from '/home/ttlhi10/colab-stage3-test-env/frontend/node_modules/react/index.js';
import {render,screen,fireEvent,act,cleanup,waitFor} from '/home/ttlhi10/colab-stage3-test-env/frontend/node_modules/@testing-library/react/dist/index.js';
import {MemoryRouter} from '/home/ttlhi10/colab-stage3-test-env/frontend/node_modules/react-router-dom/dist/index.mjs';
import {test,expect,vi,afterEach} from '/home/ttlhi10/colab-stage3-test-env/frontend/node_modules/vitest/dist/index.js';
import {LoginPage} from '/home/ttlhi10/colab-stage3-staging-deploy/frontend/src/auth/LoginPage';
import {PasswordChangePage} from '/home/ttlhi10/colab-stage3-staging-deploy/frontend/src/auth/PasswordChangePage';
import {setToken,getToken,clearToken} from '/home/ttlhi10/colab-stage3-staging-deploy/frontend/src/auth/store';
import {api} from '/home/ttlhi10/colab-stage3-staging-deploy/frontend/src/api/client';
afterEach(()=>{cleanup();clearToken();vi.unstubAllGlobals();});
async function rejectSubmit(){const form=document.querySelector('form')!;const key=Object.keys(form).find(k=>k.startsWith('__reactProps$'))!;let error;await act(async()=>{try{await (form as any)[key].onSubmit({preventDefault(){}});}catch(e){error=e;}});expect(error).toBeInstanceOf(TypeError);}
test('BUG reproduced: login network rejection leaves permanent disabled busy without message',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('network unavailable')));render(<LoginPage/>);fireEvent.change(screen.getByTestId('login-account-name'),{target:{value:'audit@example.test'}});fireEvent.change(screen.getByTestId('login-password'),{target:{value:'audit-password'}});await rejectSubmit();expect(screen.getByTestId('login-submit')).toBeDisabled();expect(screen.getByTestId('login-submit')).toHaveTextContent('확인하는 중');expect(screen.queryByRole('alert')).toBeNull();});
test('BUG reproduced: password change network rejection leaves permanent disabled busy',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new TypeError('network unavailable')));render(<MemoryRouter><PasswordChangePage/></MemoryRouter>);for(const id of ['new-password','confirm-password'])fireEvent.change(screen.getByTestId(id),{target:{value:'audit-new-password'}});await rejectSubmit();expect(screen.getByTestId('change-password')).toBeDisabled();expect(screen.getByTestId('change-password')).toHaveTextContent('변경하는 중');expect(screen.queryByRole('alert')).toBeNull();});
test('BUG reproduced: old request 401 clears new token',async()=>{let done:any;const fetch=vi.fn(()=>new Promise<Response>(r=>done=r));vi.stubGlobal('fetch',fetch);setToken('old-token');const request=api.GET('/me');await waitFor(()=>expect(fetch).toHaveBeenCalledOnce());setToken('fresh-token');done(new Response(JSON.stringify({code:'UNAUTHORIZED'}),{status:401,headers:{'Content-Type':'application/json'}}));await request;expect(getToken()).toBeNull();});
test('BUG reproduced: storage logout event leaves stale cached token',()=>{setToken('stale-token');localStorage.removeItem('colab.session.token');window.dispatchEvent(new StorageEvent('storage',{key:'colab.session.token',oldValue:'stale-token',newValue:null,storageArea:localStorage}));expect(getToken()).toBe('stale-token');});
